# Generated by Django 4.1.2 on 2023-02-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0018_alter_movies_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='film.movies'),
            preserve_default=False,
        ),
    ]
