# Generated by Django 4.1.7 on 2023-04-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0019_subscription_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_genre',
            field=models.CharField(choices=[('ACTION', 'ACTION'), ('HORROR', 'HORROR'), ('SCIENCE FRICTION', 'SCIENCE FRICTION'), ('LOVE STORY', 'LOVE STORY'), ('INDIAN', 'INDIAN'), ('COMEDY', 'COMEDY'), ('ADVENTURE', 'ADVENTURE')], default='ACTION', max_length=300),
        ),
    ]
