# Generated by Django 4.1.7 on 2023-04-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0020_alter_movies_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
