# Generated by Django 4.1.2 on 2023-04-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0021_movies_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_director',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
