# Generated by Django 4.1.7 on 2023-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0022_movies_movie_director_alter_episode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='file_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='file_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_genre',
            field=models.CharField(choices=[('ACTION', 'ACTION'), ('HORROR THRILLER', 'HORROR THRILLER'), ('SCIENCE FRICTION', 'SCIENCE FRICTION'), ('LOVE STORY', 'LOVE STORY'), ('INDIAN', 'INDIAN'), ('ACTION DETECTIVE', 'ACTION DETECTIVE'), ('COMEDY', 'COMEDY'), ('ADVENTURE', 'ADVENTURE')], default='ACTION', max_length=300),
        ),
    ]
