# Generated by Django 4.1.7 on 2023-04-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0023_episode_file_size_movies_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_genre',
            field=models.CharField(choices=[('SUPER ACTION', 'SUPER ACTION'), ('ACTION COMEDY', 'ACTION COMEDY'), ('ROMANTIC ACTION', 'ROMANTIC ACTION'), ('HORROR THRILLER', 'HORROR THRILLER'), ('SCIENCE FRICTION', 'SCIENCE FRICTION'), ('LOVE STORY', 'LOVE STORY'), ('INDIAN', 'INDIAN'), ('ACTION DETECTIVE', 'ACTION DETECTIVE'), ('COMEDY', 'COMEDY'), ('ROMANTIC COMEDY', 'ROMANTIC COMEDY'), ('ADVENTURE', 'ADVENTURE')], default='ACTION', max_length=300),
        ),
    ]
