# Generated by Django 4.1.7 on 2023-04-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0025_alter_movies_movie_status1'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='serie_director',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
