# Generated by Django 4.1.2 on 2024-12-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0028_alter_movies_movie_vj_alter_movies_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_release_year',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
