# Generated by Django 4.1.2 on 2024-12-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0029_movies_movie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='serie_status0',
            field=models.CharField(choices=[('ENGLISH SERIE', 'ENGLISH SERIE'), ('LUGANDA TRANSLATED SERIE', 'LUGANDA TRANSLATED SERIE')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_genre',
            field=models.CharField(choices=[('SUPER ACTION', 'SUPER ACTION'), ('ACTION COMEDY', 'ACTION COMEDY'), ('ROMANTIC ACTION', 'ROMANTIC ACTION'), ('HORROR THRILLER', 'HORROR THRILLER'), ('SCIENCE FRICTION', 'SCIENCE FRICTION'), ('LOVE STORY', 'LOVE STORY'), ('INDIAN', 'INDIAN'), ('ACTION DETECTIVE', 'ACTION DETECTIVE'), ('COMEDY', 'COMEDY'), ('ROMANTIC COMEDY', 'ROMANTIC COMEDY'), ('ADVENTURE', 'ADVENTURE'), ('CARTOON', 'CARTOON'), ('FAMILY MOVIE', 'FAMILY MOVIE')], default='ACTION', max_length=300),
        ),
    ]
