# Generated by Django 4.1.2 on 2024-12-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0030_series_serie_status0_alter_movies_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='serie_status0',
            new_name='serie_translation_status',
        ),
    ]
