# Generated by Django 4.2.17 on 2025-02-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0031_rename_serie_status0_series_serie_translation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='carousel_video',
            field=models.FileField(default=0, upload_to='c_videos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='serie_release_year',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
