# Generated by Django 4.2.17 on 2025-02-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0032_carousel_carousel_video_series_serie_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.ImageField(upload_to='c_pic'),
        ),
    ]
