# Generated by Django 4.1.2 on 2025-02-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0033_alter_carousel_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_VJ',
            field=models.CharField(choices=[('VJ.JUNIOR', 'VJ.JUNIOR'), ('VJ.EMMY', 'VJ.EMMY'), ('VJ.ICE.P', 'VJ.ICE.P'), ('VJ.JINGO', 'VJ.JINGO'), ('ENGLISH', 'ENGLISH'), ('VJ.ULIO', 'VJ.ULIO'), ('VJ.MARK', 'VJ.MARK'), ('VJ.KEVO', 'VJ.KEVO'), ('VJ.MARTIN K', 'VJ.MARTIN K'), ('OTHER VJs', 'OTHER VJs')], default='VJ', max_length=300),
        ),
    ]
